### ISSUE TITLE
thinkで渡されたmoveResultに何も入れないとException

### ISSUE THREAD

**Issue by shinsuke79** [yone6379/DiamondGame#10]
moveResultはUserがGameMasterに対してユーザーの「一手」を伝えるクラス。
moveResultは通常ユーザーの一手が入れられていることが期待されるが、
AIのバグで何も入らないことも考えられる。
moveResultに正しい値が入っていない場合、GameMasterが適当にコマを動かすが仕様。
Exceptionしてはならない

```
2016-03-20 16:40:28:820 HumanUser#6171f1d4  INFO    think start 
2016-03-20 16:40:28:821 UserBoard#23b64ae8  INFO      ①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⑱⑲
2016-03-20 16:40:28:822 UserBoard#23b64ae8  INFO    A                   ○                  
2016-03-20 16:40:28:823 UserBoard#23b64ae8  INFO    B                 ○  ○                
2016-03-20 16:40:28:824 UserBoard#23b64ae8  INFO    C               ○  ○  ○              
2016-03-20 16:40:28:824 UserBoard#23b64ae8  INFO    D 黄  黄  黄  黄  ○  ○  赤  赤  赤  赤
2016-03-20 16:40:28:825 UserBoard#23b64ae8  INFO    E   黄  黄  黄  ○  ○  ○  赤  赤  赤  
2016-03-20 16:40:28:826 UserBoard#23b64ae8  INFO    F     黄  黄  ○  ○  ○  ○  赤  赤    
2016-03-20 16:40:28:826 UserBoard#23b64ae8  INFO    G       黄  ○  ○  ○  ○  ○  赤      
2016-03-20 16:40:28:827 UserBoard#23b64ae8  INFO    H         ○  ○  ○  ○  ○  ○        
2016-03-20 16:40:28:827 UserBoard#23b64ae8  INFO    I           ○  ○  ○  ○  ○          
2016-03-20 16:40:28:827 UserBoard#23b64ae8  INFO    J             緑  緑  緑  緑            
2016-03-20 16:40:28:827 UserBoard#23b64ae8  INFO    K               緑  緑  緑              
2016-03-20 16:40:28:827 UserBoard#23b64ae8  INFO    L                 緑  緑                
2016-03-20 16:40:28:828 UserBoard#23b64ae8  INFO    M                   緑                  
移動元のマスを選択してください
移動元候補：K12,K10,J9,K8,J11,J7,J13,
J7
駒を移動させる軌跡を選択していきます
移動元: J7 
現在: J7 
移動先候補：I8,I6,
I6
Pieceの移動を継続しますか？(yes:続ける no:終わり reset:最初から)
no
2016-03-20 16:41:09:857 HumanUser#6171f1d4  INFO    think end result:Move [mTeam=緑チーム, mPiece=null, mMoveSpots=[]]
2016-03-20 16:41:09:857 HumanUser#6171f1d4  INFO    Think Finished.
Exception in thread "Thread-1" java.lang.NullPointerException
    at game.Board.isMoveValid(Board.java:230)
    at game.GameMaster.checkMove(GameMaster.java:187)
    at game.GameMaster.procInMove(GameMaster.java:128)
    at game.GameMaster.stateControl(GameMaster.java:56)
    at game.GameMaster.run(GameMaster.java:37)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by shinsuke79** [comment]
#5 実装中に気づいた。
